apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-config
data:
  DB_NAME: messaging_db
  DB_HOST: mysql-service  # Change from 'localhost' to 'mysql-service' for Kubernetes
  DB_PORT: "3306"
