apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
      version: green
  template:
    metadata:
      labels:
        app: django-app
        version: green
    spec:
      containers:
      - name: django-app
        image: your-dockerhub-username/django-messaging-app:v2  # New version
        ports:
        - containerPort: 8000
