pipeline {
    agent any
    
    environment {
        VENV = "${WORKSPACE}/venv"
        APP_DIR = "${WORKSPACE}/messaging_app"
    }
    
    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/steve9948/alx-backend-python.git',
                        credentialsId: 'github-credentials'
                    ]],
                    extensions: [[$class: 'CloneOption', depth: 1, noTags: true]]
                ])
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install pytest pytest-html
                '''
            }
        }
        
        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    cd ${APP_DIR}
                    mkdir -p test-reports
                    pytest --html=test-reports/report.html --self-contained-html
                '''
            }
        }

    }
    
    post {
        always {
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: "${WORKSPACE}/messaging_app/test-reports",
                reportFiles: 'report.html',
                reportName: 'Test Report'
            ])
        }
    }
}
