# Generated by Django 5.1.4 on 2025-01-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
